# Generated by Django 2.0.7 on 2018-10-28 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0005_auto_20180924_2016'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_date', models.DateField(default=datetime.date.today)),
                ('t_meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
                ('t_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
