# Generated by Django 2.0.7 on 2018-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempattend',
            name='t_meeting',
        ),
        migrations.AddField(
            model_name='tempattend',
            name='status',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
