# Generated by Django 2.0.7 on 2018-10-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_attendance', '0002_auto_20181028_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempattend',
            name='t_member',
            field=models.BigIntegerField(),
        ),
    ]
