# Generated by Django 2.0.7 on 2018-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_attendance', '0003_auto_20181028_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempattend',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
