# Generated by Django 2.0.7 on 2018-10-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsidy_priority', '0002_subsidypriority_subsidy_prio_mark'),
        ('subsidy_elig', '0003_remove_subsidyeligibility_subsidy_elig_mark'),
        ('subsidy_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsidy_elig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidy_elig.SubsidyEligibility')),
                ('subsidy_prio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidy_priority.SubsidyPriority')),
                ('subsidy_typ_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subsidy_types.SubsidyTypes')),
            ],
        ),
    ]
