# Generated by Django 2.0.7 on 2018-08-23 05:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_remove_member_house_pin'),
        ('chit', '0002_chit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chit_details_id', models.DateField(default=datetime.date.today)),
                ('chit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
                ('members_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
