# Generated by Django 2.0.7 on 2018-08-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitdetails',
            old_name='chit_id',
            new_name='chit_name',
        ),
        migrations.RenameField(
            model_name='chitdetails',
            old_name='members_id',
            new_name='members_name',
        ),
    ]
