# Generated by Django 2.0.7 on 2018-08-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housename', '0003_auto_20180821_1358'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(default='', max_length=25)),
                ('member_age', models.IntegerField()),
                ('member_education', models.CharField(default='', max_length=25)),
                ('member_job', models.CharField(default='', max_length=25)),
                ('member_phnum', models.CharField(default='', max_length=10)),
                ('member_mailid', models.CharField(default='', max_length=25)),
                ('member_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('member_social_cat', models.CharField(default='', max_length=25)),
                ('member_consideration', models.CharField(default='', max_length=25)),
                ('house_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housename.Housename')),
            ],
        ),
    ]
