# Generated by Django 2.0.7 on 2018-08-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='house_pin',
            field=models.IntegerField(default=682313),
            preserve_default=False,
        ),
    ]
