# Generated by Django 2.0.7 on 2018-08-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_house_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='house_pin',
        ),
    ]
