# Generated by Django 2.0.7 on 2018-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_member_house_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_mailid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
