# Generated by Django 2.0.7 on 2018-08-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='login_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
