# Generated by Django 2.0.7 on 2018-10-14 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit_final_install', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitfinalinstallment',
            name='chit_imonth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
