# Generated by Django 2.0.7 on 2018-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_elig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidyeligibility',
            name='subsidy_elig_mark',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
