# Generated by Django 2.0.7 on 2018-07-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_elig', '0002_subsidyeligibility_subsidy_elig_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidyeligibility',
            name='subsidy_elig_mark',
        ),
    ]
