# Generated by Django 2.0.7 on 2018-10-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_types', '0001_initial'),
        ('subsidy_elig', '0003_remove_subsidyeligibility_subsidy_elig_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidyeligibility',
            name='subsidy_ftype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subsidy_types.SubsidyTypes'),
            preserve_default=False,
        ),
    ]
