# Generated by Django 2.0.7 on 2018-10-13 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chit', '0003_chit_login_id'),
        ('chit_details', '0003_auto_20180823_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitFinalDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chit_install_amount', models.BigIntegerField()),
                ('fchit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
                ('fmember_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_details.ChitDetails')),
            ],
        ),
    ]
