# Generated by Django 2.0.7 on 2018-10-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit_final_draw', '0002_chitfinaldraw_chit_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitfinaldraw',
            name='chit_month',
        ),
    ]
