# Generated by Django 2.0.7 on 2018-10-14 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit_final_draw', '0003_remove_chitfinaldraw_chit_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitfinaldraw',
            name='chit_month',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='chitfinaldraw',
            name='chit_install_amount',
            field=models.CharField(default='', max_length=10),
        ),
    ]
