# Generated by Django 2.0.7 on 2018-08-22 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_remove_member_house_pin'),
        ('chit', '0002_chit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChitInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chit_install_amount', models.BigIntegerField()),
                ('fchit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit.Chit')),
                ('fmember_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
            ],
        ),
    ]
