# Generated by Django 2.0.7 on 2018-08-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit_installment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chitinstallment',
            old_name='fmember_id',
            new_name='fmember_name',
        ),
    ]
