# Generated by Django 2.0.7 on 2018-08-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chit_installment', '0002_auto_20180823_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitinstallment',
            name='fmember_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_details.ChitDetails'),
        ),
    ]
