# Generated by Django 2.0.7 on 2018-10-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chit_installment', '0003_auto_20180823_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitinstallment',
            name='fchit_name',
        ),
        migrations.RemoveField(
            model_name='chitinstallment',
            name='fmember_name',
        ),
        migrations.DeleteModel(
            name='ChitInstallment',
        ),
    ]
