# Generated by Django 2.0.7 on 2018-11-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_priority', '0003_auto_20181014_1509'),
        ('apply_subsidy', '0002_auto_20181109_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='fifth_prio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prio_fifth', to='subsidy_priority.SubsidyPriority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='fourth_prio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prio_fourth', to='subsidy_priority.SubsidyPriority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='sec_prio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prio_sec', to='subsidy_priority.SubsidyPriority'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='third_prio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prio_third', to='subsidy_priority.SubsidyPriority'),
            preserve_default=False,
        ),
    ]
