# Generated by Django 2.0.7 on 2018-11-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0004_auto_20181109_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='status',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
