# Generated by Django 2.0.7 on 2018-11-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180924_2016'),
        ('apply_subsidy', '0006_auto_20181109_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='applicant_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='members.Member'),
            preserve_default=False,
        ),
    ]
