# Generated by Django 2.0.7 on 2018-11-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0009_applysubsidy_address_po'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='Address_road',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='mob',
            field=models.CharField(default='', max_length=10),
        ),
    ]
