# Generated by Django 2.0.7 on 2018-11-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0011_auto_20181109_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='social_cat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
