# Generated by Django 2.0.7 on 2018-11-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0013_auto_20181109_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='special1_consideration',
            field=models.CharField(default='', max_length=20),
        ),
    ]
