# Generated by Django 2.0.7 on 2018-11-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0014_applysubsidy_special1_consideration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applysubsidy',
            name='special1_consideration',
        ),
    ]
