# Generated by Django 2.0.7 on 2018-11-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_elig', '0004_subsidyeligibility_subsidy_ftype'),
        ('apply_subsidy', '0017_auto_20181110_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='sec_elig',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='elig_sec', to='subsidy_elig.SubsidyEligibility'),
        ),
    ]
