# Generated by Django 2.0.7 on 2018-11-10 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_priority', '0003_auto_20181014_1509'),
        ('subsidy_elig', '0004_subsidyeligibility_subsidy_ftype'),
        ('apply_subsidy', '0018_applysubsidy_sec_elig'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='fifth_prio',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='prio_fifth', to='subsidy_priority.SubsidyPriority'),
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='first_prio',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='subsidy_priority.SubsidyPriority'),
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='fourth_prio',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='prio_fourth', to='subsidy_priority.SubsidyPriority'),
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='sec_prio',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='prio_sec', to='subsidy_priority.SubsidyPriority'),
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='third_elig',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='elig_third', to='subsidy_elig.SubsidyEligibility'),
        ),
        migrations.AddField(
            model_name='applysubsidy',
            name='third_prio',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='prio_third', to='subsidy_priority.SubsidyPriority'),
        ),
    ]
