# Generated by Django 2.0.7 on 2018-11-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0019_auto_20181110_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='spcl_cons',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
