# Generated by Django 2.0.7 on 2018-11-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0020_applysubsidy_spcl_cons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applysubsidy',
            name='spcl_cons',
            field=models.CharField(default='', max_length=100),
        ),
    ]
