# Generated by Django 2.0.7 on 2018-11-14 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0021_auto_20181110_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applysubsidy',
            name='spcl_cons',
        ),
    ]
