# Generated by Django 2.0.7 on 2018-11-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0022_remove_applysubsidy_spcl_cons'),
    ]

    operations = [
        migrations.AddField(
            model_name='applysubsidy',
            name='cons_widow',
            field=models.CharField(default='', max_length=100),
        ),
    ]
