# Generated by Django 2.0.7 on 2018-11-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply_subsidy', '0025_auto_20181114_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applysubsidy',
            name='login_id',
        ),
    ]
