# Generated by Django 2.0.7 on 2018-08-05 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_name', models.CharField(default='', max_length=25)),
                ('coord_hname', models.CharField(default='', max_length=25)),
                ('coord_po', models.CharField(default='', max_length=25)),
                ('coord_place', models.CharField(default='', max_length=25)),
                ('coord_phno', models.CharField(default='', max_length=10)),
                ('coord_mailid', models.CharField(default='', max_length=25)),
                ('coord_uname', models.CharField(default='', max_length=25)),
                ('coord_pwd', models.CharField(default='', max_length=25)),
                ('coord_gender', models.CharField(default='', max_length=10)),
                ('coord_dob', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
