# Generated by Django 2.0.7 on 2018-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordregistration',
            name='coord_gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10),
        ),
    ]
