# Generated by Django 2.0.7 on 2018-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator_reg', '0002_auto_20180823_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordregistration',
            name='coord_hname',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='coordregistration',
            name='coord_mailid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coordregistration',
            name='coord_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='coordregistration',
            name='coord_place',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='coordregistration',
            name='coord_po',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='coordregistration',
            name='coord_pwd',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='coordregistration',
            name='coord_uname',
            field=models.CharField(default='', max_length=45),
        ),
    ]
