# Generated by Django 2.0.7 on 2018-09-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit', '0002_chit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chit',
            name='login_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
