# Generated by Django 2.0.7 on 2018-10-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan_elig', '0001_initial'),
        ('loan_priority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_elig_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_elig.LoanEligibility')),
                ('loan_prio_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_priority.LoanPriority')),
            ],
        ),
    ]
