# Generated by Django 2.0.7 on 2018-07-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Housename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(default='', max_length=25)),
                ('house_num', models.CharField(default='', max_length=25)),
                ('house_po', models.CharField(default='', max_length=25)),
                ('house_road', models.CharField(default='', max_length=25)),
                ('house_district', models.CharField(default='Ernakulam', max_length=25)),
                ('house_state', models.CharField(default='Kerala', max_length=25)),
                ('house_adhar', models.IntegerField()),
                ('house_uname', models.CharField(default='', max_length=15)),
                ('house_pwd', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
