# Generated by Django 2.0.7 on 2018-08-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housename', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housename',
            old_name='house_road',
            new_name='house_street',
        ),
    ]
