# Generated by Django 2.0.7 on 2018-08-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housename', '0002_auto_20180821_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housename',
            name='house_adhar',
            field=models.CharField(default='', max_length=25),
        ),
    ]
