# Generated by Django 2.0.7 on 2018-09-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housename', '0003_auto_20180821_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='housename',
            name='house_mail',
            field=models.CharField(default='', max_length=25),
        ),
    ]
