# Generated by Django 2.0.7 on 2018-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housename', '0004_housename_house_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housename',
            name='house_adhar',
            field=models.CharField(default='', max_length=38),
        ),
        migrations.AlterField(
            model_name='housename',
            name='house_district',
            field=models.CharField(default='Ernakulam', max_length=50),
        ),
        migrations.AlterField(
            model_name='housename',
            name='house_mail',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='housename',
            name='house_name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='housename',
            name='house_po',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='housename',
            name='house_street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
