# Generated by Django 2.0.7 on 2018-10-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_elig', '0004_subsidyeligibility_subsidy_ftype'),
        ('subsidy_types', '0001_initial'),
        ('subsidy_priority', '0002_subsidypriority_subsidy_prio_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidypriority',
            name='subsidy_pelig',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subsidy_elig.SubsidyEligibility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidypriority',
            name='subsidy_ptype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subsidy_types.SubsidyTypes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsidypriority',
            name='subsidy_prio_mark',
            field=models.BigIntegerField(),
        ),
    ]
