# Generated by Django 2.0.7 on 2018-11-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_priority', '0003_auto_20181014_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidypriority',
            name='subsidy_pelig',
        ),
        migrations.RemoveField(
            model_name='subsidypriority',
            name='subsidy_ptype',
        ),
    ]
