# Generated by Django 2.0.7 on 2018-11-10 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisions', models.CharField(default='', max_length=250)),
                ('tdate', models.DateField(default=datetime.date.today)),
                ('meeting_ag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
    ]
