# Generated by Django 2.0.7 on 2018-08-31 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WardMembRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardmemb_name', models.CharField(default='', max_length=25)),
                ('wardmemb_hname', models.CharField(default='', max_length=25)),
                ('wardmemb_po', models.CharField(default='', max_length=25)),
                ('wardmemb_place', models.CharField(default='', max_length=25)),
                ('wardmemb_phno', models.CharField(default='', max_length=10)),
                ('wardmemb_mailid', models.CharField(default='', max_length=25)),
                ('wardmemb_uname', models.CharField(default='', max_length=25)),
                ('wardmemb_pwd', models.CharField(default='', max_length=25)),
                ('wardmemb_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10)),
                ('wardmemb_dob', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
